package com.example.quizapp;

public class Androidqs {
    String[] questions2={
            "Android is -",
            " Under which of the following Android is licensed?",
            "For which of the following Android is mainly developed?",
            "Which of the following is the first mobile phone released that ran the Android OS?",
            "Which of the following virtual machine is used by the Android operating system?",
            "Android is based on which of the following language?",
            "APK stands for -",
            "What does API stand for?",
            " Which of the following converts Java byte code into Dalvik byte code?",
            "How can we stop the services in android?",
            "What is an activity in android?",
            " How can we kill an activity in android?",
            "ADB stands for -",
            "On which of the following, developers can test the application, during developing the android applications?",
            " Which of the following kernel is used in Android?",
            " Which of the following is the first callback method that is invoked by the system during an activity life-cycle?",
            "Which of the following is not an activity lifecycle callback method?",
            "We require an AVD to create an emulator. What does AVD stand for?",
            "Does android support other languages than java?",
            "What is the use of content provider in Android?",
            " AAPT stands for -",
            "NDK stands for -",
            "Which of the following is contained in the src folder?",
            "Which of the following method is used to handle what happens after clicking a button?",
            "Which of the following android component displays the part of an activity on screen?",
            "Which of the following is the parent class of Activity?",
            "Which of the following is the parent class of service?",
            "OHA in android stands for -",
            " In which of the following tab an error is shown?",
            "In which year OHA (Open Handset Alliance) is announced?",
            "Which of the following is the name of the Android version 1.5?",
            "Which of the following is the name of the Android version 1.6?",
            "Which of the following is the topmost layer of android architecture?",
            "Which of the layer is below the topmost layer of android architecture?",
            " Which of the layer is the lowest layer of android architecture?",
            " What is contained in manifest.xml?",
            "Which of the following is not a state in the service lifecycle?",
            "As an android programmer, which version of Android should we use as a minimum development target?",
            "Which of the following is not a nickname of any android version?",
            "Which of the following is a dialog class in android?",
            " In which state the activity is, if it is not in focus, but still visible on the screen?",
            "Which of the following is the built-in database of Android?",
            "Which of the following android version is named Jelly Bean?",
            "Which of the following features are updated in Android 4.1(Jelly Bean)?",
            " Which of the following is the API level of Android version 5.0?",
            "Is it true that \"There can be only one running activity at a given time\"?",
            "Which of the following android library provides access to the database?",
            "In Android studio, which of the following callback is called when an activity starts interacting with the user?",
            " The sendStickybroadcast(intent) method in android is used to show that the intent is -",
            "Which of the following class in android displays information for a short period of time and disappears after some time?",
            "Which of the following method in android is used to log debug messages?"

    };
    String[] optiona2={
            "an operating system",
            "OSS",
            "Servers",
            "HTC Hero",
            "JVM",
            "Java",
            "Android Phone Kit",
            "Application Programming Interface",
            "Dalvik converter",
            "By using the stopSelf() and stopService() method",
            "android class",
            "Using finish() method",
            "Android debug bridge",
            "Third-party emulators",
            "MAC",
            "onClick() method",
            "onClick() method",
            "Android Virtual device",
            "Yes",
            "For storing the data in the database",
            "Android Activity Packaging Tool",
            "Native Development Kit",
            "XML",
            "onClick",
            "View",
            "context",
            "context",
            "Open Health Academy",
            "CPU",
            "2005",
            "Eclair",
            "Eclair",
            "System Libraries and Android Runtime",
            "System Libraries and Android Runtime",
            "System Libraries and Android Runtime",
            "Source code",
            "Destroyed",
            "Version 1.2 or version 1.3",
            "Donut",
            "AlertDialog",
            "Stopped state",
            "SQLite",
            "3.1",
            "User Interface",
            "21",
            "True",
            "android.content",
            "onDestroy",
            "Optional",
            "toast class",
            "Log.r()"

    };
    String[] optionb2={
            "a web browser",
            "Sourceforge",
            "Desktops",
            "Google gPhone",
            "Dalvik virtual machine",
            "C++",
            "Android Page Kit",
            "Android Programming Interface",
            "Dex compiler",
            "By using the finish() method",
            "android package",
            "Using finishActivity(int requestCode)",
            "Android delete bridge",
            "Emulator included in Android SDK",
            "Windows",
            "onCreate() method",
            "onCreate() method",
            "Android Virtual display",
            "No",
            "For sharing the data between applications",
            "Android Asset Packaging Tool",
            "New Development kit",
            "Java source code",
            "onCreate",
            "Manifest",
            "object",
            "object",
            "Open Handset Alliance",
            "Memory",
            "2007",
            "Froyo",
            "Froyo",
            "Linux Kernel",
            "Linux Kernel",
            "Linux Kernel",
            "List of strings used in the app",
            "Start",
            "Version 1.0 or version 1.1",
            "Muffin",
            "DatePicker Dialog",
            "Destroyed state",
            "MySQL",
            "2.1",
            "Lock screen improvement",
            "20",
            "False",
            "android.database",
            "onCreate",
            "Prioritize",
            "log class",
            "Log.R()"

    };
    String[] optionc2={
            "a web server",
            "Apache/MIT",
            "Laptops",
            "T - Mobile G1",
            "Simple virtual machine",
            "C",
            "Android Package Kit",
            "Android Page Interface",
            "Mobile interpretive compiler (MIC)",
            "By using system.exit() method",
            "A single screen in an application with supporting java code",
            "Both (a) and (b)",
            "Android destroy bridge",
            "Physical android phone",
            "Linux",
            "onStart() method",
            "onStart() method",
            "Active Virtual display",
            "May be",
            "For sending the data from an application to another application",
            "Android Action Packaging Tool",
            "Native Design Kit",
            "Manifest",
            "onSelect",
            "Intent",
            "contextThemeWrapper",
            "contextThemeWrapper",
            "Open Handset Application",
            "ADB Logs",
            "2006",
            "Cupcake",
            "Cupcake",
            "Applications",
            "Applications",
            "Applications",
            "Permission that the application requires",
            "Paused",
            "Version 1.6 or version 2.0",
            "Honeycomb",
            "ProgressDialog",
            "Paused state",
            "Oracle",
            "1.1",
            "New clock application",
            "11",
            "May be",
            "android.api",
            "onResume",
            "Sticky",
            "maketest class",
            "Log.d()"

    };
    String[] optiond2={
            "None of the above",
            "None of the above",
            "Mobile devices",
            "None of the above",
            "None of the above",
            "None of the above",
            "None of the above",
            "Application Page Interface",
            "None of the above",
            "None of the above",
            "None of the above",
            "Neither (a) nor (b)",
            "None of the above",
            "All of the above",
            "Redhat",
            "onRestart() method",
            "onBackPressed() method",
            "Active Virtual device",
            "Can't say",
            "None of the above",
            "None of the above",
            "None of the above",
            "None of the above",
            "None of the above",
            "Fragment",
            "None of the above",
            "contextWrapper",
            "Open Handset Association",
            "Logcat",
            "None of the above",
            "Donut",
            "Donut",
            "Applications Framework",
            "Applications Framework",
            "Applications Framework",
            "None of the above",
            "Running",
            "Version 2.3 or version 3.0",
            "Cupcake",
            "All of the above",
            "Running state",
            "None of the above",
            "4.1",
            "All of the above",
            "41",
            "Can't say",
            "None of the above",
            "onStop",
            "None of the above",
            "None of the above",
            "Log.D()"

    };
    String[] correctans2={
            "an operating system",
            "Apache/MIT",
            "Mobile devices",
            "T - Mobile G1",
            "Dalvik virtual machine",
            "Java",
            " Android Package Kit",
            "Application Programming Interface",
            "Dex compiler",
            "By using the stopSelf() and stopService() method",
            "A single screen in an application with supporting java code",
            "Both (a) and (b)",
            " Android debug bridge",
            "All of the above",
            " Linux",
            "onCreate() method",
            "onBackPressed() method",
            " Android Virtual device",
            " Yes",
            "For sending the data from an application to another application",
            "Android Asset Packaging Tool",
            "Native Development Kit",
            " Java source code",
            "onClick",
            "Fragment",
            "contextThemeWrapper",
            "contextWrapper",
            "Open Handset Alliance",
            "Logcat",
            "2007",
            "Cupcake",
            "Donut",
            "Applications",
            "Applications Framework",
            " Linux Kernel",
            "Permission that the application requires",
            "Paused",
            "Version 1.6 or version 2.0",
            "Muffin",
            "All of the above",
            "Paused state",
            " SQLite",
            " 4.1",
            "All of the above",
            "21",
            " True",
            "android.database",
            "onResume",
            "Sticky",
            "toast class",
            "Log.d()"

    };

}
