package com.example.quizapp;

public class javaqs {
    String[] questions={
            "Which of the following option leads to the portability and security of Java?",
            "Which of the following is not a Java features?",
            "The \\u0021 article referred to as a",
            "_______is used to find and fix bugs in the Java programs.",
            "Which of the following is a valid declaration of a char?",
            "What is the return type of the hashCode() method in the Object class?",
            "Which of the following is a valid long literal?",
            "What does the expression float a = 35 / 0 return?",
            "Evaluate the following Java expression, if x=3, y=5, and z=10:\n" +
                    "\n" +
                    "++z + y - y + z + x++",
            "Which of the following tool is used to generate API documentation in HTML format from doc comments in source code?",
            "Which of the following creates a List of 3 visible items and multiple selections abled?",
            "Which of the following for loop declaration is not valid?",
            "Which method of the Class.class is used to determine the name of a class represented by the class object as a String?",
            "In which process, a local variable has the same name as one of the instance variables?",
            "Which of the following is true about the anonymous inner class?",
            "Which package contains the Random class?",
            "What do you mean by nameless objects?",
            " An interface with no fields or methods is known as a ______.",
            "Which of the following is an immediate subclass of the Panel class?",
            "Which option is false about the final keyword?",
            "Which of these classes are the direct subclasses of the Throwable class?",
            "What do you mean by chained exceptions in Java?",
            "In which memory a String is stored, when we create a string using new operator?",
            "Which of the following is a marker interface?",
            "Which of the following is a reserved keyword in Java?",
            "Which keyword is used for accessing the features of a package?",
            " In java, jar stands for_____.",
            "Which of the following is false?",
            "What is the use of \\w in regex?",
            "Which of the given methods are of Object class?",
            " Which of the following is a valid syntax to synchronize the HashMap?",
            "Which of the following is a mutable class in java?",
            "What is meant by the classes and objects that dependents on each other?",
            "Which of the following code segment would execute the stored procedure \"getPassword()\" located in a database server?",
            "How many threads can be executed at a time?",
            "If three threads trying to share a single object at the same time, which condition will arise in this scenario?",
            " If a thread goes to sleep",
            "Which of the following modifiers can be used for a variable so that it can be accessed by any thread or a part of a program?",
            "In character stream I/O, a single read/write operation performs _____.",
            "What is the default encoding for an OutputStreamWriter?",
            "Which of these components are used in a Java program for compilation, debugging, and execution?",
            "Which of these literals can be contained in a float data type variable?",
            "What is BigDecimal.ONE?",
            "When an expression consists of int, double, long, float, then the entire expression will get promoted into a data type that is:",
            "Out of these statements, which ones are incorrect?",
            " When does Overloading not occur?",
            "What is it called when the child object also gets killed when the parent object is killed in the program?",
            " How does one identify if a compilation unit is an interface or class from a .class file?",
            "Out of these methods of the String class, which one can be used for testing the strings for equality?",
            "What would happen to the thread whenever the garbage collection kicks off?"
    };
    String[] optiona={
            "Bytecode is executed by JVM",
            "Dynamic",
            "Unicode escape sequence",
            "JVM",
            "char ch = '\\utea';",
            "Object",
            "ABH8097",
            "0",
            "24",
            "javap tool",
            "new List(false, 3)",
            "for ( int i = 99; i >= 0; i / 9 )",
            "getClass()",
            "Serialization",
            "It has only methods",
            "java.util package",
            "An object created by using the new keyword.",
            "Runnable Interface",
            "Applet class",
            "A final method cannot be overridden in its subclasses.",
            "RuntimeException and Error class",
            "Exceptions occurred by the VirtualMachineError",
            "Stack",
            "It returns the existing string from memory",
            "Runnable interface",
            "object",
            "package",
            "Java Archive Runner",
            "The rt.jar stands for the runtime jar",
            "Used for a whitespace character",
            "notify(), wait( long msecs ), and synchronized()",
            "Map m = hashMap.synchronizeMap();",
            "java.lang.String",
            "Tight Coupling",
            "CallableStatement cs = connection.prepareCall(\"{call.getPassword()}\");\n" +
                    "cs.executeQuery();",
            "Only one thread",
            "Time-Lapse",
            "It releases all the locks it has.",
            "global",
            "Two bytes read/write at a time.",
            "UTF-8",
            "JDK",
            "-3.4e+050",
            " it is a custom-defined statement",
            "float",
            " The Brackets () have the highest precedence",
            " When more than a single method have the same name, yet different types or number of parameters and different method signature",
            "Encapsulation",
            "Extension of the compilation unit",
            " isequals()",
            " The garbage collection won’t happen until the running of the thread"

    };
    String[] optionb={
            "The applet makes the Java code secure and portable",
            "Architecture Neutral",
            "Octal escape",
            "JRE",
            "char ca = 'tea';",
            "int",
            "L990023",
            "Not a number",
            "23",
            "javaw command",
            "new List(3, true)",
            "for ( int i = 7; i <= 77; i += 7 )",
            "intern()",
            "Variable Shadowing",
            "Objects can't be created",
            "java.lang package",
            "An object of a superclass created in the subclass.",
            "Marker Interface",
            "Window class",
            "A final class cannot be extended.",
            "Exception and VirtualMachineError class",
            "An exception caused by other exceptions",
            "String memory",
            "It creates a new string in the database",
            "Remote interface",
            "strictfp",
            "import",
            "Java Application Resource",
            "It is an optional jar file",
            "Used for a non-whitespace character",
            "wait( long msecs ), interrupt(), and notifyAll()",
            "HashMap map =hashMap.synchronizeMap();",
            "java.lang.Byte",
            "Cohesion",
            "CallabledStatement callable = conn.prepareCall(\"{call getPassword()}\");\n" +
                    "callable.executeUpdate();",
            "Multiple threads",
            "Critical situation",
            "It does not release any locks.",
            "transient",
            "Eight bytes read/write at a time.",
            "Default encoding of the host platform",
            "JVM",
            "+1.7e+308",
            "it is a wrong statement",
            "double",
            " The equal to = operator has the lowest precedence",
            "When more than a single method have the same name, the same signature, but have different numbers of signature",
            "Association",
            "Java source file header",
            " isequal()",
            "The thread would continue its operation"


    };
    String[] optionc={
            "Use of exception handling",
            "Use of pointers",
            "Hexadecimal",
            "JDK",
            "char cr = \\u0223;",
            "long",
            "904423",
            "Infinity",
            "20",
            "Javadoc tool",
            "new List(true, 3)",
            "for ( int i = 20; i >= 2; - -i )",
            "getName()",
            "Abstraction",
            "It has a fixed class name",
            "java.awt package",
            "An object without having any name but having a reference.",
            "Abstract Interface",
            "Frame class",
            "A final class cannot extend other classes.",
            "Error and Exception class",
            "Exceptions occur in chains with discarding the debugging information",
            "Heap memory",
            "It modifies the existing string in the database",
            "Readable interface",
            "main",
            "extends",
            "Java Application Runner",
            "It contains all the compiled class files",
            "Used for a word character",
            "notify(), notifyAll(), and wait()",
            "Map m1 = Collections.synchronizedMap(hashMap);",
            "java.lang.Short",
            "Loose Coupling",
            "CallableStatement cab = con.prepareCall(\"{call getPassword()}\");\n" +
                    "cab.executeQuery();",
            "Only main (main() method) thread",
            "Race condition",
            "It releases half of its locks.",
            "volatile",
            "One byte read/write at a time.",
            "UTF-12",
            "JRE",
            "-3.4e+038",
            "it is a static variable that has a value of 1 on a scale of 0",
            "long",
            "The addition operator + and the subtraction operator – have an equal precedence",
            "When more than a single method have the same signature, same name, and the same number of parameters have different types",
            "Aggregation",
            "The class and interface cannot be differentiated",
            " equals()",
            "The garbage collection and the thread don’t interfere with each other"
    };
    String[] optiond={
            "Dynamic binding between objects",
            "Object-oriented",
            "Line feed",
            "JDB",
            "char cc = '\\itea';",
            "void",
            "0xnf029L",
            "Run time exception",
            "25",
            "javah command",
            "new List(3, false)",
            "for ( int i = 2; i <= 20; i = 2* i )",
            "toString()",
            "Multi-threading",
            "It has no class name",
            "java.io package",
            "An object that has no reference.",
            "CharSequence Interface",
            "Dialog class",
            "A final method can be inherited.",
            "IOException and VirtualMachineError class",
            "None of the above",
            "Random storage space",
            "None of the above",
            "Result interface",
            "system",
            "export",
            "None of the above",
            "All the classes available in rt.jar is known to the JVM",
            "Used for a non-word character",
            "sleep( long msecs ), wait(), and notify()",
            "Map m2 = Collection.synchronizeMap(hashMap);",
            "java.lang.StringBuilder",
            "None of the above",
            "Callablestatement cstate = connect.prepareCall(\"{call getpassword()}\");\n" +
                    "cstate.executeQuery();",
            "Two threads",
            "Recursion",
            "It releases all of its lock except one.",
            "default",
            "Five bytes read/ write at a time.",
            "None of the above",
            "JIT",
            " -1.7e+308",
            " it is a static variable that has a value of 1 on a scale of 10",
            "int",
            " The division operator / has comparatively higher precedence as compared to a multiplication operator",
            "When more than a single method have the same name, the same number and types of parameters, and yet different signatures",
            "Composition",
            "The unit type must be used to postfix interface or class name",
            "equal()",
            "The thread would be paused while the running of the garbage collection"
    };
    String[] correctans={
            "Bytecode is executed by the JVM",
            "Use of pointers",
            " Unicode escape sequence",
            "JDB",
            "char ch = '\\utea';",
            "int",
            "0xnf029L",
            " Infinity",
            "25",
            "Javadoc tool",
            "new List(3, true)",
            " for ( int i = 99; i>=0; i / 9)",
            "getName()",
            "Variable Shadowing",
            "It has no class name",
            "java.util package",
            "An object that has no reference.",
            "Marker Interface",
            "Applet class",
            "A final class cannot extend other classes.",
            "Error and Exception class",
            "An exception caused by other exceptions",
            "Heap memory",
            "It returns the existing string from the memory",
            "Remote interface",
            "strictfp",
            "import",
            "None of the above",
            "It is an optional jar file.",
            "Used for a word character",
            "notify(), notifyAll(), and wait()",
            "Map m1 = Collections.synchronizedMap(hashMap);",
            "java.lang.StringBuilder",
            "Tight Coupling",
            " CallableStatement cab = con.prepareCall(\"{call getPassword()}\");\n" +
                    "cab.executeQuery();",
            "Multiple threads",
            "Race condition",
            "It does not release any locks.",
            "volatile",
            "Two bytes read/write at a time.",
            "Default encoding of the host platform",
            "JDK",
            "-3.4e+038",
            "it is a static variable that has a value of 1 on a scale of 0",
            "double",
            "The division operator / has comparatively higher precedence as compared to a multiplication operator",
            "When more than a single method have the same name, the same number and types of parameters, and yet different signatures",
            "Composition",
            "Java source file header",
            "equals()",
            "The thread would be paused while the running of the garbage collection"
    };
}
